# Generated by Django 3.2.25 on 2024-03-28 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='Email',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='Phone',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
