# Generated by Django 3.2.25 on 2024-03-29 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_auto_20240328_0133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teammember',
            name='Admin',
        ),
        migrations.AddField(
            model_name='teammember',
            name='Role',
            field=models.IntegerField(default=1),
        ),
    ]
